### ISSUE TITLE
create reservations model 

### ISSUE THREAD

**Issue by baselqyqony** [baselqyqony/hotelreservation#1]
create reservations class inside core module to represent reservation entity

**Comment by baselqyqony** [comment]
Ive created the needed class

**Comment by ZsoltToth** [comment]
I have reviewed your modifications. Please fix the following problems

- [x] RoomPrice class is confusing. Convert it to a Price class which has a amount and a currency fields. There is bult-in Currency class in Java.
- [x] ServicePrice is also confusing. RoomPrice and ServicePrice classes should  be merged into a Price class
- [x] Extends ServiceType and RoomType enumerations with unitPrice field which is a Price object. (See planets example https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html)
- [x] Move classes to model.room package
- [x] Move User class to model.user package
