### ISSUE TITLE
create reservation manager service 

### ISSUE THREAD

**Issue by baselqyqony** [baselqyqony/hotelreservation#2]
create reservation manager service interface in core module

**Comment by ZsoltToth** [comment]
I have reviewed your code and there are no exceptions. Please define and add custom exceptions to your solution. 

- [x] Place your service related exceptions into the service.exceptions package
- [x] Service interfaces should be modified to throw your custom exceptions. 
- [x] Add JavaDoc description to Services and methods.
- [x] Add package-infor.java (Package level JavaDoc)
