### ISSUE TITLE
Create Reservation Model classes

### ISSUE THREAD

**Issue by ZsoltToth** [baselqyqony/hotelreservation#3]
Design classes to represent a reservation. 
Reservations should be requested. A reservation request should contains at least the User's, the duration (arrival, departure), the number of rooms (how many rooms with how many beds, without room numbers), and a description. 

Reservations are created based on Reservation Requests. When you create a reservation you have to assign rooms to the needs of the customers (users).

**Comment by Sharif90** [comment]
I have finished the task, please review and advise.  
Thanks
